server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maps_guide_travel?useSSL=false
    username: root
    password: 1234qwer
#    driver-class-name: com.mysql.jdbc.Driver */
  jpa:
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
  application:
    name: map-place-service
endpoints:
  trace:
    enabled: true
    sensitive: false
app:
  framework:
    appConfig:
      namespace: map-place-service
      prefix: MPS